---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "pentaho-full-v0.1.0"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
  source:
    git:
      uri: "https://github.com/warpcomdev/pentaho-full"
      ref: "v0.1.0"
    contextDir: "build/pentaho"
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: "ImageStreamTag"
      name: "pentaho-full:0.1.0"
