---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    fiware.app: smartcities
    fiware.release: {{ .Release.Name }}
    fiware.module: pentaho
    fiware.tier: backend
data:
  POSTGRES_HOST: postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: postgres
  JACKRABBIT_PASSWORD: postgres
  QUARTZ_PASSWORD: postgres
  HIBERNATE_PASSWORD: postgres
  PENTAHO_PREF: {{ .Release.Name }}_
