---
apiVersion: v1
kind: Service
metadata:
  name: iot-pentaho-headless
  labels:
    fiware.app: smartcities
    fiware.module: pentaho
    fiware.tier: backend
spec:
  clusterIP: None
  selector:
    fiware.app: smartcities
    fiware.module: pentaho
    fiware.tier: backend
  ports:
  - protocol: TCP
    name: web
    targetPort: web
    port: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: iot-pentaho
  labels:
    fiware.app: smartcities
    fiware.module: pentaho
    fiware.tier: backend
spec:
  selector:
    fiware.app: smartcities
    fiware.module: pentaho
    fiware.tier: backend
  ports:
  - protocol: TCP
    name: web
    targetPort: web
    port: 7001
