---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pentaho
  labels:
    fiware.app: smartcities
    fiware.release: {{ .Release.Name }}
    fiware.module: pentaho
    fiware.tier: backend
spec:
  clusterIP: None
  selector:
    fiware.app: smartcities
    fiware.release: {{ .Release.Name }}
    fiware.module: pentaho
    fiware.tier: backend
  ports:
  - protocol: TCP
    name: web
    targetPort: web
    port: 7001
