apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-pentaho
  labels:
    fiware.app: smartcities
    fiware.release: {{ .Release.Name }}
    fiware.module: pentaho
    fiware.tier: backend
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  replicas: 2
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      fiware.app: smartcities
      fiware.release: {{ .Release.Name }}
      fiware.module: pentaho
      fiware.tier: backend
  serviceName: {{ .Release.Name }}-pentaho
  template:
    metadata:
      labels:
        fiware.app: smartcities
        fiware.release: {{ .Release.Name }}
        fiware.module: pentaho
        fiware.tier: backend
    spec:
      initContainers:
      # Create .firstboot file so the container does not try to
      # write the schema to postgres
      - name: firstboot
        image: pentaho-full:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        command:
        - /bin/bash
        args:
        - "-c"
        - "touch /opt/pentaho-server/.firstboot"
        volumeMounts:
        - name: pentaho-server
          mountPath: /opt/pentaho-server
      - name: unzip
        image: pentaho-full:0.1.0
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        command:
        - /bin/bash
        args:
        - "-c"
        - "cd /opt && unzip /tmp/pentaho-server-ce-${PENTAHO_VERSION}.zip"
        volumeMounts:
        - name: pentaho-server
          mountPath: /opt/pentaho-server
      - name: config
        image: pentaho-full:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        command:
        - /bin/bash
        args:
        - "-c"
        - >-
          /opt/config.sh "$POSTGRES_HOST" "$POSTGRES_PORT" "$PENTAHO_PREF" unused `hostname`
          > /opt/pentaho-server/schema.sql
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-credentials
        volumeMounts:
        - name: pentaho-server
          mountPath: /opt/pentaho-server
      containers:
      - name: pentaho
        image: pentaho-full:0.1.0
        ports:
        - containerPort: 7001
          name: web
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-credentials
        env:
        - name: PENTAHO_PORT
          value: "7001"
        - name: PROXY_PORT
          value: "7001"
        - name: PROXY_SCHEME
          value: http
        volumeMounts:
        - name: pentaho-server
          mountPath: /opt/pentaho-server
        - name: kettle-cache
          mountPath: /.kettle
        - name: pentaho-cache
          mountPath: /.pentaho
        - name: esapi-home
          mountPath: /home/pentaho/esapi
        - name: kettle-home
          mountPath: /home/pentaho/kettle
        livenessProbe:
          httpGet:
            path: /pentaho/Login
            port: web
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: http
          failureThreshold: 3
          periodSeconds: 15
          timeoutSeconds: 5
          initialDelaySeconds: 150
        # Not currently supported!
        # startupProbe:
        #   httpGet:
        #     path: /pentaho/Login
        #     port: web
        #     httpHeaders:
        #     - name: X-FORWARDED-PROTO
        #       value: http
        #   failureThreshold: 20
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /pentaho/Login
            port: web
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: http
          periodSeconds: 15
          successThreshold: 3
          timeoutSeconds: 5
      volumes:
      - name: pentaho-server
        emptyDir: {}
      - name: kettle-cache
        emptyDir: {}
      - name: pentaho-cache
        emptyDir: {}
      - name: esapi-home
        emptyDir: {}
      - name: kettle-home
        emptyDir: {}

